### ISSUE TITLE
back_1_kwlee

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#1]
TODO LIST
- [x] POST /api/addwaitlist API 시퀀스 다이어그램 작성
- [x] POST /api/removewaitlist: API 시퀀스 다이어그램 작성

**Comment by seo2im** [comment]
1. 서버측만 고려하면 되기 때문에 view에서 user로의 통신은 신경쓰지 않아도 됩니다.

2. Post 요청에 어떤 param의 포함되어 오는지 작성해주세요
- 예시: /api/addwaitlist에는 param으로 userid, subjectName 등등 이 같이 넘어와야 할것입니다
- param의 이름은 [DB Model](https://www.notion.so/DB-Model-83f0b5c6d2e14a8dacce2031c7ecd719) 을 참고해주세요

3. 에러상황에 대한 고려가 되어 있지 않습니다.
- 예시: /api/addwaitlist에는 userId가 잘못된 경우 등이 있을 수 있습니다. 해당 에러에 대한 response를 다른 화살표로 작성해 주세요

위 3 사항 반영해서 수정 부탁드립니다

**Comment by seo2im** [comment]
1. Db가 null을 반환한 경우 view로 실패를 response해줘야 합니다 해당 화살표을 표기해주시기 바랍니다

위 사항대로 수정 부탁드립니다

**Comment by Lks9172** [comment]
피드백 반영했습니다!
