### ISSUE TITLE
Team 스키마에 팀 설명과 프로젝트 pdf링크 넣는 것에 대한 건의

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#101]
## Description
프론트 엔드 담당인 지원님이 팀 데이터에 팀 설명을 넣는 부분이 필요하고 pdf 링크를 넣는 곳이 필요하지 않겠냐는 건의를 하셨습니다. 회의 때 얘기하고 수정할지 안할지 정하면 좋을 것 같습니다.

**Comment by seo2im** [comment]
확인 오늘 회의(월 6.28.)에서 확인하겠습니다

**Comment by atimangel** [comment]
회의 결과 페이즈2에서 처리하기로 했습니다.
