### ISSUE TITLE
매칭 이후 추가 인원 더 받기 위한 방안, 서브젝트 별 매칭 인원 변경에 대한 논의

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#165]
## Description
1. 매칭 이후 추가 인원을 더 받기 위해서
    state 값을 모두 wait_member로 변경하면 될 것 같습니다.
    state 값이 less_member은 인원이 적지만 추가 인원을 받지 않고 진행할 때 쓰기로 했고,
    progress값은 인원이 다 찼을 때 쓰기로 한 값입니다. 3명이 모였을 때 이 상태값으로 팀을 생성했는데 이걸 wait_member로 수정하면 추가 인원을 받을 수 있다는 신호가 될 수 있습니다.

2. 서브젝트 별 매칭 인원 변경
    이너서클내에서 팀원을 모집해야하는 프로젝트는 minishell, miniRT, cub3d, webserv(2~3), ft_irc(2~3), ft_transcendence(3~5)등이 있습니다. 

### Todo
- [ ] conetent

**Comment by hminn** [comment]
- minishell, miniRT, cub3d => 4명
- webserv(23), ft_irc(23) => 4~5명
- ft_transcendence(3~5) => 3~5명

**Comment by atimangel** [comment]
DB에서 sort해서 불러오기, 매칭 우선순위들을 이때 고려하고, 불러온 이후엔 인원수 별로 나눠서 팀 생성만 하기
