### ISSUE TITLE
login router 시퀀스 다이어그램 작성

### ISSUE THREAD

**Issue by minjakim** [Matching42/Matching42-back#18]
## Description
client에서 POST /api/login 시퀀스 다이어그램 작성

### Todo
- [ ] 시퀀스 다이어그램 작성

**Comment by minjakim** [comment]
Matching42 서비스에 신규, 기존, 만료 등의 상황으로 나누어 생각해보면
- 신규의 경우 캠퍼스 42seoul 한정으로 접근권한을 분리 할지~
- 42 intra 를 이용 첫 인증이 성공적으로 이루어진 다음 자체 토큰 발급(만료는 블랙홀 기준)에 대한 부분.
- 위를 전제로 자체 토큰이 만료 되거나 삭제가 되지 않았다면 이 후의 로그인 과정 생략 되고 페이지 접속시 자체토큰의 확인 과정으로 대체

**Comment by seo2im** [comment]
assign은 해당 이슈의 담당자이므로 본인으로 설정해 주시고 이후 PR을 생성할 때(시퀀스 다이어그램 작업은 PR이 없으므로 해당 과정이 없습니다) reviewer로 저를 설정해주시면 됩니다

**Comment by minjakim** [comment]
확인 했습니다~!!

**Comment by minjakim** [comment]
- 42seoul 한정 (42seoul no 이용)
- 자체토큰 발급 JWT
- 토큰 유효기간 1달 (남아있는 블랙홀이 1달 이내인 경우 블랙홀 만료 기간)
- 토큰 확인과정을 다뤄줘야 함~

**Comment by seo2im** [comment]
시퀀스 작성이 마무리되셨으면 close 후 다음 작업으로 진행해주시면 됩니다.
