### ISSUE TITLE
back1_hokim

### ISSUE THREAD

**Issue by hokim2407** [Matching42/Matching42-back#2]
TODO LIST
- [x] POST /api/addwaitteam 시퀀스 다이어그램 작성
- [x] POST /api/deletewaittem 시퀀스 다이어그램 작성

**Comment by seo2im** [comment]
1. POST 요청에서 parameter를 무엇을 받아오는지 view -> controller 화살표에 표기해주시고

2. 실패의 경우(db null 반환 등등) view로 fail을 response하는 화살표를 따로 표기해주시기 바랍니다.

위 두사항 관련해서 수정 부탁드립니다

**Comment by hokim2407** [comment]
수정했습니다!
