### ISSUE TITLE
swagger API 문서 작성

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#62]
## Description
swagger를 이용하여 API 문서화 진행
- GET /user/:userId
- POST /addmember

### Todo
- [x] GET /user/:userId
- [x] POST /addmember

**Comment by seo2im** [comment]
PR review 확인 요망

**Comment by hminn** [comment]
Swagger 문서 추가 수정 사항 발견되어 Reopen하고 수정하겠습니다.
