### ISSUE TITLE
API Sequence Diagram /team/{teamId}

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#7]
Description
팀 정보 요청 API 시퀀스 다이아그램 작성

TODO LIST

- [ ]  문제 파악하기
- [ ]  DB 모델 체크하기
- [ ]  질문 목록 만들기
- [ ]  질문하기

**Comment by atimangel** [comment]
팀 정보를 불러오는 API다.
1. 토큰이 필요한 일인가?.
    로그인을 해야지 볼 수 있는 정보라면 토큰이 필요할텐데 공개된 정보 아닌가?
    그러면 토큰 인증을 생략해도 되지 않나?
2. 어떤 쿼리를 써야지 team id 로 팀 정보를 탐색할 수 있을까?
    getUser? getTeam?
3. TeamId가 null이면 뭘 반환해야하지?

**Comment by atimangel** [comment]
1. user > controller | 유저의 팀 정보 요청
>GET /team/{teamId};
2. controller > DB | Team 요청 쿼리
>getTeam(id)
3. DB | Team정보가 존재하는가?
    DB > Controller
    1.  없음  NULL 반환
    2. 있음 id와 일치하는 Team 정보 반환
 4. Controller > User |teamId 와 일치하는 정보 반환

**Comment by atimangel** [comment]
1. user > controller | user의 팀 리스트 정보 요청
> GET /team/
2. controller > DB | Team 요청 쿼리
> DB에 있는 모든 팀 정보 요청(어떤 쿼리 써야하는지 모름)

3.DB | Team 정보가 존재하는가?
3-1. DB > Controller | 없음
>NULL반환

3-2 DB > Controller | 있음
>팀 정보 리스트 반환// 배열로?

4.Controller > User | 팀 리스트 정보 전달

**Comment by atimangel** [comment]
https://github.com/Matching42/Matching42_practice/issues/22 여기에 이슈 발급하고 작성하고 있었습니다.

**Comment by atimangel** [comment]
![image](https://user-images.githubusercontent.com/54225321/118076133-731f0a80-b3ec-11eb-9eaa-baa00301d2e8.png)![image](https://user-images.githubusercontent.com/54225321/118076156-7fa36300-b3ec-11eb-93a7-cab3ab65c3d8.png)

**Comment by seo2im** [comment]
1. DB가 Null 반환시에 view로 전달하는 로직도 필요합니다. 표기해주시기 바랍니다.

위 사항 수정 부탁드립니다.


추가> 원칙적으로는 해당 두 다이어그램은 하나로 표현되어야 합니다만, 흐름 파악에 문제는 없으니 종합시에 제가 합치도록 하겠습니다.

**Comment by atimangel** [comment]
https://www.figma.com/file/Yj5KSO7B57Fv7aHmW7fT50/Untitled?node-id=61%3A153
수정했습니다

**Comment by seo2im** [comment]
링크 오류인지 접속이 되지 않습니다. 접속이 되지 않습니다. 확인 부탁드립니다
