### ISSUE TITLE
API Sequence Diagram 작성

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#8]
**Description**
- Client에서 GET /api/user/{id} 요청이 왔을 때의 시퀀스 다이어그램 작성
- Client에서 POST /api/addmember 요청이 왔을 때의 시퀀스 다이어그램 작성

**TODO**
- [x]  GET /api/user/{id} 시퀀스 다이어그램 작성
- [x]  POST /api/addmember 시퀀스 다이어그램 작성

**Comment by hminn** [comment]
- GET /api/user/{id} 시퀀스 다이어그램
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/eb93cedc-4718-4338-8137-38558154cfbd/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/eb93cedc-4718-4338-8137-38558154cfbd/Untitled.png)

- POST /api/addmember 시퀀스 다이어그램
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/675857bf-c183-462f-82c6-fdea6cfe1e84/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/675857bf-c183-462f-82c6-fdea6cfe1e84/Untitled.png)

**Comment by seo2im** [comment]
1. POST요청에 어떤 파라미터가 담겨오는지 표기해 주시고
(addmember요청을 서버에서 처리하기 위한 최소한의 파라미터들 표기, 예> teamId, userid)

2. DB에서 NULL이 반환되거나 작업을 실패한 경우 경우에 view로 보낼 reponse를 따로 표기해 주셔야 합니다

위 두사항 관련해서 수정 부탁드립니다

**Comment by hminn** [comment]
예 알겠습니다!
