### ISSUE TITLE
GET /team/{teamID} swagger 문서 작성

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#90]
## Description
GET /team, GET /team/{teamID} 컨트롤러가 어떻게 작동되는지 알려주는 문서입니다.
swagger로 볼 수 있게 되어있습니다.

### Todo

- [x] 문서는 이미 만들어져 있으니 새로운 브랜치 만들어서 푸쉬하기

**Comment by seo2im** [comment]
master로 연결되었습니다.
그리고 #48 과 동일 이슈인데 이것만 처리하면 될까요?

**Comment by atimangel** [comment]
@seo2im 네 #48로 푸쉬가 안돼서 새로 만든 이슈라서 이것만 처리해주시면 됩니다.

**Comment by atimangel** [comment]
master로 연결돼있던 PR development로 바꿨습니다.
